name: test CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key:
            ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json')
            }}

      - name: install
        run: npm ci

      - name: build
        run: npm run build

      - name: lint
        run: npm run lint

      - name: jest testing
        run: npm test

  cypress-run:
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key:
            ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json')
            }}

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
