name: test CI

on: [pull_request]

jobs:
  test:
    name: Jest & RTL Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key:
            ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json')
            }}

      - name: install
        run: npm ci

      - name: build
        run: npm run build

      - name: lint
        run: npm run lint

      - name: jest testing
        run: npm test

  cypress-run:
    name: Cypress Tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key:
            ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json')
            }}

      - name: Cypress run
        run: npm run cy:run
        continue-on-error: false

      - name: Copy Videos and ScreenShots
        run: |
          mkdir public
          cp -r cypress/videos public/videos
          cp -r cypress/Screenshots public/Screenshots
