name: test CI
'on':
  - pull_request
jobs:
  test:
    name: Jest & RTL Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: >-
            ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json')
            }}
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: lint
        run: npm run lint
      - name: jest testing
        run: npm test
  cypress-run:
    name: Cypress Tests
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress.io
        uses: cypress-io/github-action@v2.7.0
        with:
          browser: chrome
          config: 'pageLoadTimeout=100000,baseUrl=http://localhost:3000'
          build: npm build

          start: npm start
          with:
            env:
              super_secret: ${{ secrets.SuperSecret }}
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
